const DRX = require('./DRX')
const Registration = require('./Registration')
const ErrorReporting = require('./ErrorReporting')
const Functionality = require('./Functionality')
const ModemInfo = require('./ModemInfo')
const ModeOfOperation = require('./ModeOfOperation')
const NetworkErrorReporting = require('./NetworkErrorReporting')
const PacketDomainEvents = require('./PacketDomainEvents')
const PDPContext = require('./PDPContext')
const PLMNSelection = require('./PLMNSelection')
const SignalQuality = require('./SignalQuality')
const SupportedCommands = require('./SupportedCommands')
const SupportedRadio = require('./SupportedRadio')
const USIM = require('./USIM')
const PINCode = require('./PINCode')
const NeighbouringCells = require('./NeighbouringCells')
const CurrentBand = require('./CurrentBand')
const IndicatorControl = require('./IndicatorControl')
const TLSCredentials = require('./TLSCredentials')

module.exports = {
  api: target => {
    DRX(target)
    Registration(target)
    ErrorReporting(target)
    Functionality(target)
    ModemInfo(target)
    ModeOfOperation(target)
    NetworkErrorReporting(target)
    PacketDomainEvents(target)
    PDPContext(target)
    PLMNSelection(target)
    SignalQuality(target)
    SupportedCommands(target)
    SupportedRadio(target)
    USIM(target)
    PINCode(target)
    NeighbouringCells(target)
    CurrentBand(target)
    IndicatorControl(target)
    TLSCredentials(target)
  }
}
