name: Test and Release

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install latest npm
        run: |
          sudo npm install -g npm@
          npm config set update-notifier false
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Test
        run: npm test
      - name: Semantic release
        continue-on-error: true
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i --no-save semantic-release@next
          npx semantic-release
