name: Test and Release

on: push

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Test
        run: npm test
  linux:
    runs-on: ubuntu-latest
    needs: windows
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Test
        run: npm test
      - name: Semantic release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i --no-save semantic-release@next
          npx semantic-release
