name: Test and Release

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install latest npm
        run: |
          sudo npm install -g npm@
          npm config set update-notifier false
      - name: Install dependencies
        run: npm ci --no-audit
      - name: Test
        run: npm test
      - name: Semantic release
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          # FIXME: remove use of pinned semantic-release when https://github.com/pvdlg/env-ci/pull/101 is merged
          npm i --no-save 'git+https://github.com/bifravst/semantic-release.git#next-with-env-ci-4.1.1'
          npx semantic-release
